const photos = {
  home:'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&w=1400&q=85',
  joo:'https://images.unsplash.com/photo-1601050690597-df0568f70950?auto=format&fit=crop&w=1200&q=85',
  marsiling:'https://images.unsplash.com/photo-1552566626-52f8b828add9?auto=format&fit=crop&w=1200&q=85',
  bugis:'https://images.unsplash.com/photo-1562565652-a0d8f0c59eb4?auto=format&fit=crop&w=1200&q=85',
  chinatown:'https://images.unsplash.com/photo-1515003197210-e0cd71810b5f?auto=format&fit=crop&w=1200&q=85'
};
const routeImages = {
  'joo-chiat':[photos.joo,'https://images.unsplash.com/photo-1563245372-f21724e3856d?auto=format&fit=crop&w=900&q=85','https://images.unsplash.com/photo-1559339352-11d035aa65de?auto=format&fit=crop&w=900&q=85'],
  marsiling:[photos.marsiling,'https://images.unsplash.com/photo-1526318896980-cf78c088247c?auto=format&fit=crop&w=900&q=85','https://images.unsplash.com/photo-1547592180-85f173990554?auto=format&fit=crop&w=900&q=85'],
  bugis:[photos.bugis,'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&w=900&q=85','https://images.unsplash.com/photo-1552566626-52f8b828add9?auto=format&fit=crop&w=900&q=85'],
  chinatown:[photos.chinatown,'https://images.unsplash.com/photo-1534422298391-e4f8c172dddb?auto=format&fit=crop&w=900&q=85','https://images.unsplash.com/photo-1551218808-94e220e084d2?auto=format&fit=crop&w=900&q=85']
};
const trails = {
  'joo-chiat': { label:'01', name:'Joo Chiat', kicker:'Eat your way home', intro:'A warm, walkable trail through kitchen tools, vadai, popiah, curry puffs, spices and the ice cream memories that make a neighbourhood feel like home.', dates:'22 Nov · 7, 10, 12, 17, 19 Dec', time:'9:30 – 11:00 am', meeting:'Geylang Serai Market, first floor', image:photos.joo, note:'Food is memory, made edible.', tags:['Kitchenware','Spice trade','Hawker memories'], stops:[
    ['5B','Kitchen tools & kueh moulds','46 Joo Chiat Road, Singapore 427369','Treasure hunt for matching tools. Find the tool that belongs to a prepared food image, then snap a photo.','20 min','5B has stocked classic Singaporean kitchen tools, kueh moulds and the melamine hawkerware we all recognise since 2004.'],
    ['02','The Original Vadai Shop','82 Joo Chiat Road, Singapore 427379','Taste vadai and talk about lentils, spice routes and the Chinese-influenced ingredients that found their way into local versions.','15 min','A takeaway kiosk with roots in the Geylang Serai Hari Raya bazaars of the 1990s.'],
    ['03','Kway Guan Huat Popiah','95 Joo Chiat Road, Singapore 427389','Share popiah memories: family parties, the first bite, and the rituals around rolling your own.','10 min','Founded in 1938, this third-generation family business carries a recipe from Fujian, China.'],
    ['04','Sha Zah Confectionery','105 Joo Chiat Road, Singapore 427398','The great curry puff question: fried or baked, meat or no meat, egg or no egg?','10–15 min','A family-run bakery known for XL beef rendang curry puffs and banana balls since 1997.'],
    ['05','Zam Zam Trading','119 Joo Chiat Road, Singapore 427408','Learn the native names of common spices and see how wholesale grocers keep food traditions stocked.','15 min','A small, bustling wholesale grocery — one of several that give Joo Chiat its pantry-like character.'],
    ['06','Chip Guan Heng','69 Joo Chiat Place, Singapore 427787','End with ice cream and a conversation about disappearing carts, childhood treats and what “home” tastes like.','15 min','Founded in 1970 by Goh Sing Yam, Chip Guan Heng grew from a provision shop into a local ice cream supplier.'] ] },
  marsiling:{ label:'02', name:'Marsiling', kicker:'Places change. Food remembers.', intro:'A neighbourhood trail about everyday markets, hawker skill, a bus ride through change and the stories that travel with food.', dates:'Dates to be confirmed', time:'3:00 – 6:30 pm', meeting:'Marsiling Lane Market, near POSB ATM', image:photos.marsiling, note:'Heritage can move.', tags:['Market hunt','Bus 856','Hawker heritage'], stops:[
    ['01','Nenek’s Market Riddle Hunt','20 Marsiling Lane, Singapore 730020','Teams of 3–5 solve ten riddles across the market: fish feed, kerupuk, dried chilli, flowers, herbal sweets and more.','40 min','Opened in 1975, Marsiling Lane Market was the first market serving the estate. Slow down and notice the whole ecosystem.'],
    ['02','Tea break & answer reveal','Marsiling Lane Market & Cooked Food Centre','Sort your discoveries into ingredient, household item, tool, remedy or community service. Share the item that surprised you most.','20 min','The wet market and cooked-food section form a practical one-stop space for daily life and neighbourly exchange.'],
    ['03','Teo Chap Bee Eating House','19 Marsiling Lane, #01-329, Singapore 730019','Observe the sequence of Indian-Muslim food preparation: pour, shape, cook, check texture, serve.','20 min','Griddle work makes tacit knowledge visible — timing, touch and repetition learned through practice.'],
    ['04','Bus 856 · the transition','Marsiling Lane bus stop 46129 → Marsiling Mall 46541','Use the ride as a prompt: when a town centre is redeveloped, what happens to hawkers, customers and food memories?','20 min','The route connects a 1975 neighbourhood market to a newer centre that received hawkers from Old Woodlands Town Centre.'],
    ['05','Find the Old Woodlands Hawkers','Marsiling Mall, Level 1, 4 Woodlands Street 12','Three missions: find a relocated stall, identify a dish across generations and spot a traditional preparation skill.','30 min','Around 80% of the old town centre’s 68 hawkers moved to Marsiling Mall. Can heritage move too?'],
    ['06','Dinner & closing reflection','Marsiling Mall Hawker Centre','Choose a stall, share a meal and answer: What moved with the hawkers, and what may have been lost?','45 min','Food heritage survives through documentation — and through conscious choices, conversations and continued patronage.'] ] },
  bugis:{ label:'03', name:'Bugis', kicker:'A neighbourhood in layers', intro:'From hawker centre to mosque, textile shops and teh tarik: follow the food, faith and trades that shaped Kampong Gelam.', dates:'Dates to be confirmed', time:'3:00 – 6:30 pm', meeting:'Albert Centre Market & Food Centre', image:photos.bugis, note:'Living heritage, still moving.', tags:['Kampong Gelam','Textiles','Teh tarik'], stops:[
    ['01','Food Heritage Detective','Albert Centre, 270 Queen Street, Singapore 180270','Find three foods or drinks tied to different communities. Record what they are, where they come from and what makes them distinctive.','25 min','Everyday food is a living archive — heritage survives in recipes, businesses and repeated meals.'],
    ['02','Walk through time','Queen Street','Match old photographs with their present-day equivalents, then notice how hygiene, community, food and interaction have shifted.','20 min','A visual way to see how Singapore’s modernisation changed the street without erasing its past.'],
    ['03','Singapore Zam Zam','697–699 North Bridge Road, Singapore 198675','Observe murtabak, briyani or prata and discuss why traditional foods survive as neighbourhoods change.','20 min','Indian-Muslim food businesses form an essential thread in Bugis’ multicultural food landscape.'],
    ['04','Arab Street trades','Arab Street, Singapore 199700','Spot batik, fabrics, carpets, fragrance, traditional clothing and shophouse details. Which trade could survive another 20 years?','20 min','Traditional businesses can continue without freezing a neighbourhood in the past.'],
    ['05','Sultan Mosque & Bussorah Street','3 Muscat Street → Bussorah Street','Read the golden dome and minarets, then imagine Bussorah as a Hajj departure point: food, lodging, money, supplies and guidance.','40 min','Kampong Gelam’s built heritage and pilgrimage history frame its food and trade culture.'],
    ['06','Malay Heritage Centre','85 Sultan Gate, Singapore 198501','Choose one element of Malay heritage to preserve and make a 30-second case for it.','30 min','A structured museum stop connecting food, architecture, religion, material culture and community history.'],
    ['07','Bhai Sarbat','21 Bussorah Street, Singapore 199439','End over teh tarik with the question: which kind of heritage is hardest to preserve?','25 min','The everyday ritual of a drink break is part of what keeps Kampong Gelam’s living heritage alive.'] ] },
  chinatown:{ label:'04', name:'Chinatown', kicker:'A food culture in motion', intro:'Look closer at the ingredients, objects, stories and rituals behind one of Singapore’s most layered neighbourhoods.', dates:'Dates to be confirmed', time:'3:00 – 6:30 pm', meeting:'Chinatown Complex, Smith Street stairs', image:photos.chinatown, note:'The past has a taste.', tags:['Wet market','Shophouses','Hawker culture'], stops:[
    ['01','Chinatown Complex · taste the past','335 Smith Street, Level 2, Singapore 050335','Find foods and pastries significant to Chinese culture — lor mee, egg tarts, dim sum and more — then share what they mean to you.','30 min','Modern Singapore is multicultural; this stop makes space for Chinese food culture to be noticed and appreciated.'],
    ['02','Objects & old-world details','335 Smith Street, Level 1','Spot traditional costumes, sundries and vintage objects. Find their names, uses and the stories they carry.','20 min','Culture appears in many forms: objects and everyday things can be relics of the past.'],
    ['03','Basement market','335 Smith Street, Basement','Observe ingredients and traditional items that don’t often appear in supermarkets. Watch the relationship between vendors and regulars.','20 min','Wet markets offer a rare glimpse into food handling, commerce and social rhythms that are easy to overlook.'],
    ['04','Chinatown Heritage Centre','48 Pagoda Street, Singapore 059207','Explore recreated shophouse quarters and connect household objects to the dishes and food culture just encountered.','20 min','For early immigrants, food was survival, memory and community bonding in cramped shared quarters.'],
    ['05','Smith Street murals','30 Smith Street, Singapore 058944','Find Chinatown Home, Cat in Murals, Cantonese Opera and Chinatown Market, then look for snacks, tea and trinkets nearby.','20 min','Street art creates a vivid contrast with preserved shophouses — two ways of remembering everyday life.'],
    ['06','Buddha Tooth Relic Temple','288 South Bridge Road, Singapore 058840','Pause for a short exposition, the temple’s architecture and the old radio that once carried stories to Singaporeans.','10 min','Built in 2007, the temple sits among complexes, HDB blocks and shophouses at the heart of Chinatown.'],
    ['07','Maxwell Food Centre','1 Kadayanallur Street, Singapore 069184','Close with a wide-angle view of Chinatown’s food culture, from Hainanese chicken rice to newer international offerings.','30 min','Opened as a wet market in 1928 and redeveloped as a food centre in 1987, Maxwell keeps changing while feeding the city.'] ] }
};
function nav(active='') { return `<header class="site-header"><a class="brand" href="#/"><span class="brand-mark">✦</span><span>FOOD TRAILS</span></a><nav class="nav"><a href="#/joo-chiat" class="${active==='joo-chiat'?'active':''}">Joo Chiat</a><a href="#/marsiling" class="${active==='marsiling'?'active':''}">Marsiling</a><a href="#/bugis" class="${active==='bugis'?'active':''}">Bugis</a><a href="#/chinatown" class="${active==='chinatown'?'active':''}">Chinatown</a></nav></header>` }
function home() { return `${nav()}<main class="page"><section class="hero"><div><div class="eyebrow">Singapore · food · memory · place</div><h1>Take the long way home.</h1><p class="intro">Four food trails through the city’s living heritage. Follow the smells, stories, hands and small rituals that make a place more than a place.</p><div class="hero-actions"><a class="button" href="#/joo-chiat">Explore the trails <span>↗</span></a><a class="button alt" href="#/marsiling">Start with Marsiling</a></div></div><div class="hero-photo"><img src="${photos.home}" alt="A lively restaurant interior"><div class="photo-note"><strong>Made of memories</strong><span>Stories are better when shared around a table.</span></div></div></section><section><div class="section-head"><div><div class="eyebrow">Choose your pace</div><h2>Four ways to wander.</h2></div><p>Each trail is a guided invitation to look closer, taste something new and leave with a story you can pass on.</p></div><div class="route-bar">${Object.entries(trails).map(([slug,t])=>`<a class="route-tab" href="#/${slug}"><span class="mono">${t.label}</span><strong>${t.name}</strong><small>${t.kicker}</small></a>`).join('')}</div></section><section class="callout"><div><div class="eyebrow">The shared idea</div><h2>Food heritage is made of our collective memories.</h2></div><p>Support local businesses. Ask respectful questions. Talk about the food your family remembers. Places change, but the stories can keep travelling — through what we cook, buy, taste and tell.</p></section></main><footer class="footer"><p>MOF Food Trails · Singapore</p><span class="mono">Walk slowly. Notice everything.</span></footer>` }
function trail(slug) { const t=trails[slug]; const images=routeImages[slug]; return `${nav(slug)}<main class="page"><section class="route-hero"><div><div class="eyebrow">Trail ${t.label} · ${t.kicker}</div><h1>${t.name}</h1><p class="intro">${t.intro}</p></div><div class="route-meta"><div class="meta-block"><div class="mono">When</div><p>${t.dates}<br>${t.time}</p></div><div class="meta-block"><div class="mono">Meet at</div><p>${t.meeting}</p></div><div class="meta-block"><div class="mono">Route mood</div><p>${t.tags.join(' · ')}</p></div></div></section><section class="route-shell"><div class="section-head"><div><div class="eyebrow">The route</div><h2>Stop, look, taste.</h2></div><p>Move at the speed of conversation. Ask before photographing, keep queues clear and let the neighbourhood lead.</p></div><div class="timeline">${t.stops.map((s,i)=>`<article class="stop"><div class="stop-num">${String(i+1).padStart(2,'0')}</div><div class="stop-card"><div><div class="eyebrow">${s[4]}</div><h3>${s[1]}</h3><p class="address">${s[2]}</p><p>${s[3]}</p><p><strong>Why it matters:</strong> ${s[5]}</p><div class="stop-details"><span>● Slow observation</span><span>● Shared stories</span></div></div><img src="${images[i % images.length]}" alt="${s[1]}" loading="lazy"></div></article>`).join('')}</div></section><section class="callout"><div><div class="eyebrow">Take it with you</div><h2>${t.note}</h2></div><div><p>Before you go, choose one detail to remember and one local business to support. The best souvenir is a story told accurately, warmly and with permission.</p>${t.tags.map(x=>`<span class="pill">${x}</span>`).join('')}</div></section></main><footer class="footer"><p>MOF Food Trails · ${t.name}</p><a class="mono" href="#/">Back to all trails ↗</a></footer>` }
function render() { const slug=location.hash.replace('#/',''); document.getElementById('app').innerHTML=trails[slug]?trail(slug):home(); window.scrollTo(0,0); }
window.addEventListener('hashchange',render); render();
