const photos = {
  home:'guide-media/image81.png',
  joo:'guide-media/image43.jpg',
  marsiling:'guide-media/image11.png',
  bugis:'guide-media/image94.jpg',
  chinatown:'guide-media/image137.jpg'
};
const routeImages = {
  'joo-chiat':['guide-media/image43.jpg','guide-media/image113.jpg','guide-media/image119.jpg','guide-media/image92.jpg','guide-media/image15.jpg','guide-media/image121.jpg','guide-media/image14.jpg'],
  marsiling:['guide-media/image11.png','guide-media/image81.png','guide-media/image49.png','guide-media/image112.png','guide-media/image123.png','guide-media/image6.png'],
  bugis:['guide-media/image94.jpg','guide-media/image61.png','guide-media/image120.png','guide-media/image125.jpg','guide-media/image10.png','guide-media/image108.jpg','guide-media/image76.png'],
  chinatown:['guide-media/image137.jpg','guide-media/image102.jpg','guide-media/image103.jpg','guide-media/image22.jpg','guide-media/image59.jpg','guide-media/image130.jpg','guide-media/image99.jpg']
};
const routeTitles = {'joo-chiat':'Taste the details.','marsiling':'Move with the memories.','bugis':'Stop, look, taste.','chinatown':'Read the neighbourhood.'};
const cardAccents = {
  'joo-chiat':['Kitchen tools','A crisp, spiced bite','Roll your own memory','The curry puff debate','Inside the neighbourhood pantry','A pushcart legacy','A sweet final stop'],
  marsiling:['Riddle hunt','Market rhythm','Hands at the griddle','A ride through change','Heritage detectives','Dinner with a question'],
  bugis:['Three cultures, one table','Then & now','Indian-Muslim foodways','Threads of a living street','A place of gathering','A street of arrivals','Pull, pour, share'],
  chinatown:['Taste the past','Objects with a story','Under the market floor','Lives behind the shophouse','Walls that remember','A quiet pause','The table keeps growing']
};
const cardPrompts = {
  'joo-chiat':['Spot the tool behind the dish.','Listen for the crunch.','Ask about the family recipe.','Choose your side.','Name one spice you recognise.','Trace the route from pushcart to shop.','Share your childhood flavour.'],
  marsiling:['Find it, frame it, leave it be.','Sort what the market makes possible.','Watch timing become technique.','Notice what travels between places.','Prove the story before you share it.','Eat, then answer what changed.'],
  bugis:['Name the culture in the bowl.','Put yesterday beside today.','Watch a dish carry many influences.','Find a trade worth keeping.','Look up with respect.','Imagine the pilgrim’s checklist.','End with the sound of a pour.'],
  chinatown:['Choose the bite with a backstory.','Find an object your supermarket cannot replace.','Notice the language of the market.','Step inside another generation.','Follow the colour to the next story.','Look for the details between monuments.','Finish where the neighbourhood gathers.']
};
const trails = {
  'joo-chiat': { label:'01', name:'Joo Chiat', kicker:'Eat your way home', intro:'A warm, walkable trail through kitchen tools, vadai, popiah, curry puffs, spices and the ice cream memories that make a neighbourhood feel like home.', dates:'22 Nov · 7, 10, 12, 17, 19 Dec', time:'9:30 – 11:00 am', meeting:'Geylang Serai Market, first floor', image:photos.joo, note:'Food is memory, made edible.', guide:'Follow the scent of toasted spice and the small tools behind Singapore’s favourite bites.', moments:['Look closely at the hands and tools that keep recipes in motion.','Trade a family food memory with someone new.'], tags:['Kitchenware','Spice trade','Hawker memories'], stops:[
    ['5B','Kitchen tools & kueh moulds','46 Joo Chiat Road, Singapore 427369','Treasure hunt for matching tools. Find the tool that belongs to a prepared food image, then snap a photo.','20 min','5B has stocked classic Singaporean kitchen tools, kueh moulds and the melamine hawkerware we all recognise since 2004.'],
    ['02','The Original Vadai Shop','82 Joo Chiat Road, Singapore 427379','Taste vadai and talk about lentils, spice routes and the Chinese-influenced ingredients that found their way into local versions.','15 min','A takeaway kiosk with roots in the Geylang Serai Hari Raya bazaars of the 1990s.'],
    ['03','Kway Guan Huat Popiah','95 Joo Chiat Road, Singapore 427389','Share popiah memories: family parties, the first bite, and the rituals around rolling your own.','10 min','Founded in 1938, this third-generation family business carries a recipe from Fujian, China.'],
    ['04','Sha Zah Confectionery','105 Joo Chiat Road, Singapore 427398','The great curry puff question: fried or baked, meat or no meat, egg or no egg?','10–15 min','A family-run bakery known for XL beef rendang curry puffs and banana balls since 1997.'],
    ['05','Zam Zam Trading','119 Joo Chiat Road, Singapore 427408','Learn the native names of common spices and see how wholesale grocers keep food traditions stocked.','15 min','A small, bustling wholesale grocery — one of several that give Joo Chiat its pantry-like character.'],
    ['06','Fei Fei Wanton Mee','45 Joo Chiat Place, Singapore 427769','Follow the story from a 1940s pushcart to a family-run wanton noodle shop, then notice what a name can carry across generations.','15 min','Fei Fei Wanton Mee began with Chan Sin Yam and continues today under his grandson, Lim Loon Huat.'],
    ['07','Chip Guan Heng','69 Joo Chiat Place, Singapore 427787','End with ice cream and a conversation about disappearing carts, childhood treats and what “home” tastes like.','15 min','Founded in 1970 by Goh Sing Yam, Chip Guan Heng grew from a provision shop into a local ice cream supplier.'] ] },
  marsiling:{ label:'02', name:'Marsiling', kicker:'Places change. Food remembers.', intro:'A neighbourhood trail about everyday markets, hawker skill, a bus ride through change and the stories that travel with food.', dates:'Dates to be confirmed', time:'3:00 – 6:30 pm', meeting:'Marsiling Lane Market, near POSB ATM', image:photos.marsiling, note:'Heritage can move.', guide:'Start with a market riddle, ride through a changing estate and listen for what hawkers carried with them.', moments:['Notice the ordinary objects that make a market a neighbourhood.','Ask what travelled when the old town centre closed.'], tags:['Market hunt','Bus 856','Hawker heritage'], stops:[
    ['01','Nenek’s Market Riddle Hunt','20 Marsiling Lane, Singapore 730020','Teams of 3–5 solve ten riddles across the market: fish feed, kerupuk, dried chilli, flowers, herbal sweets and more.','40 min','Opened in 1975, Marsiling Lane Market was the first market serving the estate. Slow down and notice the whole ecosystem.'],
    ['02','Tea break & answer reveal','Marsiling Lane Market & Cooked Food Centre','Sort your discoveries into ingredient, household item, tool, remedy or community service. Share the item that surprised you most.','20 min','The wet market and cooked-food section form a practical one-stop space for daily life and neighbourly exchange.'],
    ['03','Teo Chap Bee Eating House','19 Marsiling Lane, #01-329, Singapore 730019','Observe the sequence of Indian-Muslim food preparation: pour, shape, cook, check texture, serve.','20 min','Griddle work makes tacit knowledge visible — timing, touch and repetition learned through practice.'],
    ['04','Bus 856 · the transition','Marsiling Lane bus stop 46129 → Marsiling Mall 46541','Use the ride as a prompt: when a town centre is redeveloped, what happens to hawkers, customers and food memories?','20 min','The route connects a 1975 neighbourhood market to a newer centre that received hawkers from Old Woodlands Town Centre.'],
    ['05','Find the Old Woodlands Hawkers','Marsiling Mall, Level 1, 4 Woodlands Street 12','Three missions: find a relocated stall, identify a dish across generations and spot a traditional preparation skill.','30 min','Around 80% of the old town centre’s 68 hawkers moved to Marsiling Mall. Can heritage move too?'],
    ['06','Dinner & closing reflection','Marsiling Mall Hawker Centre','Choose a stall, share a meal and answer: What moved with the hawkers, and what may have been lost?','45 min','Food heritage survives through documentation — and through conscious choices, conversations and continued patronage.'] ] },
  bugis:{ label:'03', name:'Bugis', kicker:'A neighbourhood in layers', intro:'From hawker centre to mosque, textile shops and teh tarik: follow the food, faith and trades that shaped Kampong Gelam.', dates:'Dates to be confirmed', time:'3:00 – 6:30 pm', meeting:'Albert Centre Market & Food Centre', image:photos.bugis, note:'Living heritage, still moving.', guide:'Read Kampong Gelam as a living menu: hawker stalls, prayer, fabric, perfume and the ritual pour of teh tarik.', moments:['Compare what has changed on the street with what has stayed.','Make space for the people and places that hold community together.'], tags:['Kampong Gelam','Textiles','Teh tarik'], stops:[
    ['01','Food Heritage Detective','Albert Centre, 270 Queen Street, Singapore 180270','Find three foods or drinks tied to different communities. Record what they are, where they come from and what makes them distinctive.','25 min','Everyday food is a living archive — heritage survives in recipes, businesses and repeated meals.'],
    ['02','Walk through time','Queen Street','Match old photographs with their present-day equivalents, then notice how hygiene, community, food and interaction have shifted.','20 min','A visual way to see how Singapore’s modernisation changed the street without erasing its past.'],
    ['03','Singapore Zam Zam','697–699 North Bridge Road, Singapore 198675','Observe murtabak, briyani or prata and discuss why traditional foods survive as neighbourhoods change.','20 min','Indian-Muslim food businesses form an essential thread in Bugis’ multicultural food landscape.'],
    ['04','Arab Street trades','Arab Street, Singapore 199700','Spot batik, fabrics, carpets, fragrance, traditional clothing and shophouse details. Which trade could survive another 20 years?','20 min','Traditional businesses can continue without freezing a neighbourhood in the past.'],
    ['05','Sultan Mosque & Bussorah Street','3 Muscat Street → Bussorah Street','Read the golden dome and minarets, then imagine Bussorah as a Hajj departure point: food, lodging, money, supplies and guidance.','40 min','Kampong Gelam’s built heritage and pilgrimage history frame its food and trade culture.'],
    ['06','Malay Heritage Centre','85 Sultan Gate, Singapore 198501','Choose one element of Malay heritage to preserve and make a 30-second case for it.','30 min','A structured museum stop connecting food, architecture, religion, material culture and community history.'],
    ['07','Bhai Sarbat','21 Bussorah Street, Singapore 199439','End over teh tarik with the question: which kind of heritage is hardest to preserve?','25 min','The everyday ritual of a drink break is part of what keeps Kampong Gelam’s living heritage alive.'] ] },
  chinatown:{ label:'04', name:'Chinatown', kicker:'A food culture in motion', intro:'Look closer at the ingredients, objects, stories and rituals behind one of Singapore’s most layered neighbourhoods.', dates:'Dates to be confirmed', time:'3:00 – 6:30 pm', meeting:'Chinatown Complex, Smith Street stairs', image:photos.chinatown, note:'The past has a taste.', guide:'Begin below street level, then climb through objects, murals and dishes that keep Chinatown’s stories visible.', moments:['Find the history hiding in an ingredient, object or storefront.','Connect a dish on today’s table to a life lived before it.'], tags:['Wet market','Shophouses','Hawker culture'], stops:[
    ['01','Chinatown Complex · taste the past','335 Smith Street, Level 2, Singapore 050335','Find foods and pastries significant to Chinese culture — lor mee, egg tarts, dim sum and more — then share what they mean to you.','30 min','Modern Singapore is multicultural; this stop makes space for Chinese food culture to be noticed and appreciated.'],
    ['02','Objects & old-world details','335 Smith Street, Level 1','Spot traditional costumes, sundries and vintage objects. Find their names, uses and the stories they carry.','20 min','Culture appears in many forms: objects and everyday things can be relics of the past.'],
    ['03','Basement market','335 Smith Street, Basement','Observe ingredients and traditional items that don’t often appear in supermarkets. Watch the relationship between vendors and regulars.','20 min','Wet markets offer a rare glimpse into food handling, commerce and social rhythms that are easy to overlook.'],
    ['04','Chinatown Heritage Centre','48 Pagoda Street, Singapore 059207','Explore recreated shophouse quarters and connect household objects to the dishes and food culture just encountered.','20 min','For early immigrants, food was survival, memory and community bonding in cramped shared quarters.'],
    ['05','Smith Street murals','30 Smith Street, Singapore 058944','Find Chinatown Home, Cat in Murals, Cantonese Opera and Chinatown Market, then look for snacks, tea and trinkets nearby.','20 min','Street art creates a vivid contrast with preserved shophouses — two ways of remembering everyday life.'],
    ['06','Buddha Tooth Relic Temple','288 South Bridge Road, Singapore 058840','Pause for a short exposition, the temple’s architecture and the old radio that once carried stories to Singaporeans.','10 min','Built in 2007, the temple sits among complexes, HDB blocks and shophouses at the heart of Chinatown.'],
    ['07','Maxwell Food Centre','1 Kadayanallur Street, Singapore 069184','Close with a wide-angle view of Chinatown’s food culture, from Hainanese chicken rice to newer international offerings.','30 min','Opened as a wet market in 1928 and redeveloped as a food centre in 1987, Maxwell keeps changing while feeding the city.'] ] }
};
function nav(active='') { return `<div class="announcement">FOOD IS A MAP OF WHERE WE’VE BEEN · FOUR SINGAPORE TRAILS</div><header class="site-header"><nav class="nav nav-left"><a href="#/joo-chiat" class="${active==='joo-chiat'?'active':''}">Joo Chiat</a><a href="#/marsiling" class="${active==='marsiling'?'active':''}">Marsiling</a></nav><a class="brand" href="#/"><span class="brand-mark">✦</span><span>FOOD TRAILS</span></a><nav class="nav nav-right"><a href="#/bugis" class="${active==='bugis'?'active':''}">Bugis</a><a href="#/chinatown" class="${active==='chinatown'?'active':''}">Chinatown</a></nav></header>` }
function home() { return `${nav()}<main class="page"><section class="hero"><div><div class="eyebrow">Singapore · food · memory · place</div><h1>Take the long way home.</h1><p class="intro">Four food trails through the city’s living heritage. Follow the smells, stories, hands and small rituals that make a place more than a place.</p><div class="hero-actions"><a class="button" href="#/joo-chiat">Explore the trails <span>↗</span></a></div></div><div class="hero-photo"><div class="hero-badge"><span class="mono">Singapore</span><strong>Made<br>of<br>memories</strong><span>food · place · people</span></div></div></section><section><div class="section-head"><div><div class="eyebrow">Choose your pace</div><h2>Four ways to wander.</h2></div><p>Each trail is a guided invitation to look closer, taste something new and leave with a story you can pass on.</p></div><div class="route-bar">${Object.entries(trails).map(([slug,t])=>`<a class="route-tab" href="#/${slug}"><span class="mono">${t.label}</span><strong>${t.name}</strong><small>${t.kicker}</small></a>`).join('')}</div></section><section class="callout"><div><div class="eyebrow">The shared idea</div><h2>Food heritage is made of our collective memories.</h2></div><p>Support local businesses. Ask respectful questions. Talk about the food your family remembers. Places change, but the stories can keep travelling — through what we cook, buy, taste and tell.</p></section></main><footer class="footer"><p>MOF Food Trails · Singapore</p><div class="partner-lockup"><a href="https://www.foodmuseumsg.com/" target="_blank" rel="noreferrer"><img class="partner-logo" src="https://static.wixstatic.com/media/88187a_b822eb62c8364231b4ac12405a76e0fc~mv2.png" alt="Museum of Food"></a><span class="partner-x">×</span><a href="https://www.suss.edu.sg/" target="_blank" rel="noreferrer"><img class="partner-logo" src="https://static.wixstatic.com/media/88187a_51b6943097b6424a8a4dc10f55d0290f~mv2.png" alt="Singapore University of Social Sciences"></a></div></footer>` }
const locationSearch = {
  'Kitchen tools & kueh moulds':'5B Joo Chiat',
  'Nenek’s Market Riddle Hunt':'Marsiling Lane Market',
  'Tea break & answer reveal':'Marsiling Lane Market',
  'Bus 856 · the transition':'Bus 856 Marsiling',
  'Find the Old Woodlands Hawkers':'Marsiling Mall',
  'Dinner & closing reflection':'Marsiling Mall Hawker Centre',
  'Food Heritage Detective':'Albert Centre Market & Food Centre',
  'Walk through time':'Queen Street Singapore',
  'Arab Street trades':'Arab Street Singapore',
  'Sultan Mosque & Bussorah Street':'Sultan Mosque Singapore',
  'Chinatown Complex · taste the past':'Chinatown Complex',
  'Objects & old-world details':'Chinatown Complex',
  'Basement market':'Chinatown Complex',
  'Smith Street murals':'Smith Street Singapore'
};
function locationUrl(stop) { return 'https://www.google.com/search?q=' + encodeURIComponent(locationSearch[stop[1]] || stop[1]); }
function trail(slug) { const t=trails[slug]; const images=routeImages[slug]; return `${nav(slug)}<main class="page"><section class="route-hero"><div><div class="eyebrow">Trail ${t.label} · ${t.kicker}</div><h1>${t.name}</h1><p class="intro">${t.intro}</p></div><div class="route-meta"><div class="meta-block"><div class="mono">When</div><p>${t.dates}<br>${t.time}</p></div><div class="meta-block"><div class="mono">Meet at</div><p>${t.meeting}</p></div><div class="meta-block"><div class="mono">Route mood</div><p>${t.tags.join(' · ')}</p></div></div></section><section class="route-shell"><div class="section-head"><div><div class="eyebrow">The route</div><h2>${routeTitles[slug]}</h2></div><p>${t.guide}</p></div><div class="timeline">${t.stops.map((s,i)=>`<article class="stop"><div class="stop-num">${String(i+1).padStart(2,'0')}</div><div class="stop-card"><div><div class="eyebrow">${cardAccents[slug][i]}</div><h3><a class="location-link" href="${locationUrl(s)}" target="_blank" rel="noreferrer">${s[1]}</a></h3><p class="address">${s[2]}</p><p>${s[3]}</p><p><strong>Why it matters:</strong> ${s[5]}</p><div class="stop-details"><span>● ${cardPrompts[slug][i]}</span><span>◷ ${s[4]}</span></div></div><img src="${images[i]}" alt="${s[1]}" loading="lazy"></div></article>`).join('')}</div></section><section class="callout"><div><div class="eyebrow">Take it with you</div><h2>${t.note}</h2></div><div><p>Before you go, choose one detail to remember and one local business to support. The best souvenir is a story told accurately, warmly and with permission.</p>${t.tags.map(x=>`<span class="pill">${x}</span>`).join('')}</div></section></main><footer class="footer"><p>MOF Food Trails · ${t.name}</p><div class="partner-lockup"><a href="https://www.foodmuseumsg.com/" target="_blank" rel="noreferrer"><img class="partner-logo" src="https://static.wixstatic.com/media/88187a_b822eb62c8364231b4ac12405a76e0fc~mv2.png" alt="Museum of Food"></a><span class="partner-x">×</span><a href="https://www.suss.edu.sg/" target="_blank" rel="noreferrer"><img class="partner-logo" src="https://static.wixstatic.com/media/88187a_51b6943097b6424a8a4dc10f55d0290f~mv2.png" alt="Singapore University of Social Sciences"></a></div></footer>` }
function render() { const slug=location.hash.replace('#/',''); document.getElementById('app').innerHTML=trails[slug]?trail(slug):home(); window.scrollTo(0,0); }
const trailOrder = Object.keys(trails);
const renderTrail = trail;
trail = function(slug) {
  const index = trailOrder.indexOf(slug);
  const previous = trailOrder[(index - 1 + trailOrder.length) % trailOrder.length];
  const next = trailOrder[(index + 1) % trailOrder.length];
  const pagination = `<nav class="trail-pagination" aria-label="Trail navigation"><a class="trail-pagination-link" href="#/${previous}"><span class="mono">Previous trail</span><strong>&larr; ${trails[previous].name}</strong></a><a class="trail-pagination-link next" href="#/${next}"><span class="mono">Next trail</span><strong>${trails[next].name} &rarr;</strong></a></nav>`;
  return renderTrail(slug).replace('<section class="callout">', pagination + '<section class="callout">');
};
window.addEventListener('hashchange',render); render();
